export enum NotificationType {
  TRANSFER_SUBMITTED = 'TRANSFER_SUBMITTED',
  TRANSFER_APPROVED = 'TRANSFER_APPROVED',
  TRANSFER_REJECTED = 'TRANSFER_REJECTED',
  TRANSFER_COMPLETED = 'TRANSFER_COMPLETED',
  LOW_STOCK_ALERT = 'LOW_STOCK_ALERT',
  STALE_TRANSFER_REMINDER = 'STALE_TRANSFER_REMINDER',
}
